package Day18;
import java.util.*;

public class ExceptionsDemo {

	public static void main(String[] args) {
		
		//Example 1
		System.out.println("program started .....");
		
		Scanner sc = new Scanner(System.in);
//		System.out.println("Enter a number");
//		int num = sc.nextInt();
//		System.out.println(100/num);//Arithmetic Exception
//		
//		System.out.println("program is completed .....");
//		System.out.println("program is exited .....");
      
		
//		Example 2
//	ArrayIndexOutOfBoundException Example
		/*int arr[] = new int[5];
		
		System.out.println("Enter the position (0-4): ");
		int pos = sc.nextInt();
		System.out.println("Enter the value which u want to add: ");
		int value = sc.nextInt();
		arr[pos]=value;
		System.out.println(arr[pos]);
		
		System.out.println("program is completed .....");
		System.out.println("program is exited .....");
		*/
		
		
//		Example 3
		
		/*String s = "welcome";
		
		int num = Integer.parseInt(s);//NumberFormatException
		System.out.println(num);
		
		System.out.println("program is completed .....");
		System.out.println("program is exited .....");
		*/
		
//		Example 4
		
		/*String s = null;
		System.out.println(s.length());//NullPpointerException
		
		
		System.out.println("program is completed .....");
		System.out.println("program is exited .....");
		*/
		
		
		
		
		
		
		
		
	}

}
